# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 05:31
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. 10 digits allowed.", regex='^\\+?1?\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=5, unique=True)),
                ('alert_level', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Devices')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Ports'),
        ),
        migrations.AddField(
            model_name='alert',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Data'),
        ),
        migrations.AddField(
            model_name='alert',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Mobile'),
        ),
    ]
