# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 09:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. 12 digits allowed.", regex='^\\+?1?\\d{12}$')]),
        ),
    ]
