# Generated by Django 2.0.5 on 2018-09-29 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180928_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Data')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Mobile')),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='to',
        ),
        migrations.AlterField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(blank=None, default=datetime.date.today),
        ),
    ]
