# Generated by Django 2.0.5 on 2018-09-29 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180929_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='data',
        ),
        migrations.AddField(
            model_name='ports',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
